### ISSUE TITLE
How do you display long text?

### ISSUE THREAD

**Issue by Sabirjan** [F0RIS/sweet-alert-dialog#5]
长文字怎么显示？我看超过两行就后面的不显示。
How do you display long text? I see more than two lines on the back does not show.

**Comment by F0RIS** [comment]
Put ur long text in message field instead of title
Example
![image](https://user-images.githubusercontent.com/10178982/27828300-320461c8-60c4-11e7-9132-9da90fddaf23.png)

And u can create custom view and set it via setCustomView method
Example
![image](https://user-images.githubusercontent.com/10178982/27828314-4d51e0ea-60c4-11e7-8093-df16f2ea66ac.png)

**Comment by CWlf** [comment]
I use setTitleText() for title and setContentText() for message but it is also very short text. :(

**Comment by DhanushkaBasnayaka** [comment]
you can add text like this 
` final TextView editText = new TextView(context);
        editText.setText(content);
        SweetAlertDialog dialog = new SweetAlertDialog(context, SweetAlertDialog.ERROR_TYPE)
                .setTitleText(title)
                .setCustomView(editText);
        dialog.show();`

**Comment by Sabirjan** [comment]
OK, Thanks
